# Copyright (c) Spectro Cloud
# SPDX-License-Identifier: Apache-2.0

version: 2

project_name: palette-mcp-server

builds:
  - skip: true

dockers_v2:
  - dockerfile: Dockerfile
    images:
      - "public.ecr.aws/palette-ai/palette-mcp-server"
    tags:
      - "{{ .Tag }}"
      - latest
    extra_files:
      - pyproject.toml
      - uv.lock
      - src/
      - README.md
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      VERSION: "{{.Version}}"
    flags:
      - "--pull"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

report_sizes: true
release:
  disable: false
